### ISSUE TITLE
[BUG] Build fails on ESPHome 2026.5+: ClimateTraits::set_supports_* removed

### ISSUE THREAD

**Issue by TrooperDuper** [TrooperDuper/espar-airtronic-esphome#12]
## Summary
 
`EsparCanComponent::traits()` calls `ClimateTraits::set_supports_current_temperature(true)` and `ClimateTraits::set_supports_action(true)`. Both setters were **removed** from `ClimateTraits` in ESPHome 2026.5, so the component fails to compile on current ESPHome.
 
## Symptom
 
Build fails while compiling `espar_can.cpp`:
 
```
src/esphome/components/espar_can/espar_can.cpp: In member function
'virtual esphome::climate::ClimateTraits esphome::espar_can::EsparCanComponent::traits()':
error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_current_temperature'
error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_action'
*** [.pioenvs/espar-heater/src/esphome/components/espar_can/espar_can.cpp.o] Error 1
```
 
## Root cause
 
ESPHome 2026.5 replaced the per-capability boolean setters with a feature-flag bitmask (`ClimateFeature` enum in `climate_mode.h`, applied via `ClimateTraits::add_feature_flags(...)`).
 
## Fix
 
```cpp
// before
traits.set_supports_current_temperature(true);
traits.set_supports_action(true);
 
// after
traits.add_feature_flags(climate::CLIMATE_SUPPORTS_CURRENT_TEMPERATURE |
                         climate::CLIMATE_SUPPORTS_ACTION);
```
 
## Affected
 
- File: `esphome/components/espar_can/espar_can.cpp`, `EsparCanComponent::traits()`.
- Breaks the build on `main` for ESPHome 2026.5+.
## Environment
 
- ESPHome 2026.5.3, ESP32 (WeAct CAN485 V1.0), Arduino framework.
## Fix status
 
Fixed on branch `fix/esphome-2026-compat`. Pending merge to `main`.
